package suda.sudamodweather.dao.greendao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 *
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig weekForeCastDaoConfig;
    private final DaoConfig realWeatherDaoConfig;
    private final DaoConfig hourForeCastDaoConfig;
    private final DaoConfig aqiDaoConfig;
    private final DaoConfig zhishuDaoConfig;
    private final DaoConfig useAreaDaoConfig;

    private final WeekForeCastDao weekForeCastDao;
    private final RealWeatherDao realWeatherDao;
    private final HourForeCastDao hourForeCastDao;
    private final AqiDao aqiDao;
    private final ZhishuDao zhishuDao;
    private final UseAreaDao useAreaDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        weekForeCastDaoConfig = daoConfigMap.get(WeekForeCastDao.class).clone();
        weekForeCastDaoConfig.initIdentityScope(type);

        realWeatherDaoConfig = daoConfigMap.get(RealWeatherDao.class).clone();
        realWeatherDaoConfig.initIdentityScope(type);

        hourForeCastDaoConfig = daoConfigMap.get(HourForeCastDao.class).clone();
        hourForeCastDaoConfig.initIdentityScope(type);

        aqiDaoConfig = daoConfigMap.get(AqiDao.class).clone();
        aqiDaoConfig.initIdentityScope(type);

        zhishuDaoConfig = daoConfigMap.get(ZhishuDao.class).clone();
        zhishuDaoConfig.initIdentityScope(type);

        useAreaDaoConfig = daoConfigMap.get(UseAreaDao.class).clone();
        useAreaDaoConfig.initIdentityScope(type);

        weekForeCastDao = new WeekForeCastDao(weekForeCastDaoConfig, this);
        realWeatherDao = new RealWeatherDao(realWeatherDaoConfig, this);
        hourForeCastDao = new HourForeCastDao(hourForeCastDaoConfig, this);
        aqiDao = new AqiDao(aqiDaoConfig, this);
        zhishuDao = new ZhishuDao(zhishuDaoConfig, this);
        useAreaDao = new UseAreaDao(useAreaDaoConfig, this);

        registerDao(WeekForeCast.class, weekForeCastDao);
        registerDao(RealWeather.class, realWeatherDao);
        registerDao(HourForeCast.class, hourForeCastDao);
        registerDao(Aqi.class, aqiDao);
        registerDao(Zhishu.class, zhishuDao);
        registerDao(UseArea.class, useAreaDao);
    }

    public void clear() {
        weekForeCastDaoConfig.getIdentityScope().clear();
        realWeatherDaoConfig.getIdentityScope().clear();
        hourForeCastDaoConfig.getIdentityScope().clear();
        aqiDaoConfig.getIdentityScope().clear();
        zhishuDaoConfig.getIdentityScope().clear();
        useAreaDaoConfig.getIdentityScope().clear();
    }

    public WeekForeCastDao getWeekForeCastDao() {
        return weekForeCastDao;
    }

    public RealWeatherDao getRealWeatherDao() {
        return realWeatherDao;
    }

    public HourForeCastDao getHourForeCastDao() {
        return hourForeCastDao;
    }

    public AqiDao getAqiDao() {
        return aqiDao;
    }

    public ZhishuDao getZhishuDao() {
        return zhishuDao;
    }

    public UseAreaDao getUseAreaDao() {
        return useAreaDao;
    }

}
